In [17]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [ ]:
df = pd.read_csv("student-mat.csv", sep=";")
df = df[["age","absences","freetime","Medu", "G1","G2","G3"]]

predict = "G3"
X = np.array(df.drop([predict], axis=1))
y = np.array(df[predict])

In [27]:
# x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1)


In [ ]:
# model = linear_model.LinearRegression()
# model.fit(x_train, y_train)
# acc = model.score(x_test, y_test)

# print(acc)


In [37]:
# model.predict([x_test[0]])

array([12.89090745])

In [38]:
# x_test[0]

array([15,  6,  3,  2, 11, 13], dtype=int64)

In [39]:
# y = -0.18057911*15 + 0.04138008*6 + 0.12750052*3 + 0.0393772*2 + 0.17533637*11 + 0.96603524*13
# print(y)

12.488007979999999


In [36]:
# model.intercept_

0.402899545699114

In [35]:
# model.coef_

array([-0.18057911,  0.04138008,  0.12750052,  0.0393772 ,  0.17533637,
        0.96603524])

In [34]:
# predicted = model.predict(x_test)
# for i in range(len(predicted)):
#     print(f"Real: {y_test[i]}, Predicted: {predicted[i]}")
#     print("-------------------------------------------")


Real: 14, Predicted: 12.890907454510886
-------------------------------------------
Real: 9, Predicted: 9.33040433012198
-------------------------------------------
Real: 0, Predicted: 6.1004501721768465
-------------------------------------------
Real: 14, Predicted: 12.09553342155203
-------------------------------------------
Real: 15, Predicted: 14.666036708286697
-------------------------------------------
Real: 10, Predicted: 10.275777315442795
-------------------------------------------
Real: 0, Predicted: 0.1629233279850948
-------------------------------------------
Real: 10, Predicted: 9.36830426999399
-------------------------------------------
Real: 8, Predicted: 5.908052118921296
-------------------------------------------
Real: 0, Predicted: -0.7668371053602252
-------------------------------------------
Real: 18, Predicted: 18.67581901050437
-------------------------------------------
Real: 10, Predicted: 9.775439840942001
-------------------------------------------
Real

In [35]:
#test for the highest prediction
EPOCH = 100
best = 0
for i in range(EPOCH):
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
    model = linear_model.LinearRegression()
    model.fit(x_train, y_train)
    acc = model.score(x_test, y_test)
    if acc>best:
        best = acc



In [36]:
best

0.9235886028814412

In [37]:
#Part random state
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=123)
model = linear_model.LinearRegression()
model.fit(x_train, y_train)
acc = model.score(x_test, y_test)
print(f"Model accuracy: {acc}")


Model accuracy: 0.88326339241702
